# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f112aac54d4018d519eff0045053fc70433330a1456c36fd9cf85eedd29d95a8d136e5b7ee6976a20a173ac1067b6e2148fc46068ac708861ece6713e06827

test:
  secret_key_base: 374de6deb2738409434f294e2b622152213df346c12d661374613f35d2394fe38c46c93eab10b828c87fd0906fd119af0bc43721f77c07d3a7f8f984cfe8ccee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
